# fly.toml app configuration file generated for app-agriculture on 2025-06-03T01:15:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-agriculture'
primary_region = 'gig'

[build]

[env]
  DATABASE_HOST=postgres
  DATABASE_PORT=5432
  DATABASE_USERNAME=agriculture
  DATABASE_PASSWORD=agriculture
  DATABASE_NAME=agriculture
  JWT_SECRET_KEY=20132006df45aae3602581bf57715ff88f07f46fbaf2b9039c30ff
  JWT_EXPIRATION_TIME=3600

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
